# -*- coding: utf-8 -*-
"""deepfake_api_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmFFHi5tn_vZ1kXfdJjJPIDsqyRUzWCH
"""

!pip install flask flask-cors  # ✅ Run this once

!pip install facenet-pytorch

!wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
!unzip -o ngrok.zip
!chmod +x ngrok

!./ngrok config add-authtoken 2vH5Y3jnN6raKg8Lw8059bxAmtT_fqqAinwD2aczNLJXziMM

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn

class HybridDeepfakeDetector(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2)
        )
        self.rnn = nn.GRU(64 * 32 * 32, 128, batch_first=True)
        transformer_layer = nn.TransformerEncoderLayer(d_model=128, nhead=4)
        self.transformer = nn.TransformerEncoder(transformer_layer, num_layers=1)
        self.fc = nn.Sequential(
            nn.Linear(128, 64), nn.ReLU(),
            nn.Linear(64, 1), nn.Sigmoid()
        )

    def forward(self, x):
        b = x.size(0)
        x = self.cnn(x)
        x = x.view(b, -1).unsqueeze(1)
        _, h_n = self.rnn(x)
        x = h_n.permute(1, 0, 2)
        x = self.transformer(x).squeeze(1)
        return self.fc(x)

import time
from flask import Flask, request, jsonify
from flask_cors import CORS
import os, uuid, cv2, threading
from facenet_pytorch import MTCNN
from torchvision import transforms

app = Flask(__name__)
CORS(app)  # ✅ Enable CORS for all routes

UPLOAD_FOLDER = "/content/uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridDeepfakeDetector().to(device)
model.load_state_dict(torch.load("/content/drive/MyDrive/deepfake_project/hybrid_detector.pt", map_location=device))
model.eval()

mtcnn = MTCNN(image_size=128, margin=0, keep_all=True, device=device)
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

@app.route("/predict", methods=["POST"])
def predict():
    if "video" not in request.files:
        return jsonify({"error": "No video uploaded"}), 400

    file = request.files["video"]
    filename = f"{uuid.uuid4()}.mp4"
    video_path = os.path.join(UPLOAD_FOLDER, filename)
    file.save(video_path)

    cap = cv2.VideoCapture(video_path)
    frame_count = 0
    face_tensor = None

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        if frame_count % 5 == 0:
            rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            faces = mtcnn(rgb)
            if faces is not None:
                face = faces[0]
                face = transform(face.permute(1, 2, 0).cpu().numpy()).unsqueeze(0).to(device)
                face_tensor = face
                break
        frame_count += 1
    cap.release()

    if face_tensor is None:
        return jsonify({
            "prediction": "Fake",
            "confidence": 0.05,
            "reason": "No face detected in any frame.",
            "inference_time": 0.0,
            "model_used": "Hybrid Transformer v1.0"
        })

    start = time.time()
    with torch.no_grad():
        output = model(face_tensor).item()
    end = time.time()

    prediction = "Real" if output > 0.5 else "Fake"
    confidence = round(output if prediction == "Real" else 1 - output, 2)
    inference_time = round(end - start, 3)

    return jsonify({
        "prediction": prediction,
        "confidence": confidence,
        "reason": f"Face detected in {frame_count} frames checked.",
        "inference_time": inference_time,
        "model_used": "Hybrid Transformer v1.0"
    })

# Start Flask
def run_flask():
    app.run(host="0.0.0.0", port=5000)

threading.Thread(target=run_flask).start()

import time
import requests
import subprocess

# Start ngrok in background
subprocess.Popen(["./ngrok", "http", "5000"])
time.sleep(5)

# Fetch the public URL
try:
    res = requests.get("http://localhost:4040/api/tunnels").json()
    url = res['tunnels'][0]['public_url']
    print("✅ Public ngrok URL:", url)
except Exception as e:
    print("❌ Failed to fetch ngrok URL:", e)

import threading

def run_flask():
    app.run(host="0.0.0.0", port=5000)

threading.Thread(target=run_flask).start()

import time, subprocess, requests

subprocess.Popen(["./ngrok", "http", "5000"])
time.sleep(5)

try:
    res = requests.get("http://localhost:4040/api/tunnels").json()
    url = res["tunnels"][0]["public_url"]
    print("✅ NGROK URL:", url)
except Exception as e:
    print("❌ Could not get ngrok URL", e)

!pip install flask flask-cors pyngrok > /dev/null

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
import uuid, os

app = Flask(__name__)
CORS(app)  # ✅ Enables CORS for React

UPLOAD_FOLDER = "/content/uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@app.route("/predict", methods=["POST"])
def predict():
    if "video" not in request.files:
        return jsonify({"error": "No video uploaded"}), 400

    # Save video
    file = request.files["video"]
    filename = f"{uuid.uuid4()}.mp4"
    file.save(os.path.join(UPLOAD_FOLDER, filename))

    # Dummy response
    return jsonify({
        "prediction": "Fake",
        "confidence": 0.92,
        "reason": "This is a demo response.",
        "inference_time": 0.321,
        "model_used": "Hybrid Transformer v1.0"
    })

