# -*- coding: utf-8 -*-
"""face_extraction_mtcnn..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtxn7bGDXz3_ue-1tF-SgIBpHoYQT56n
"""

!pip install facenet-pytorch
!pip install opencv-python
!pip install tqdm

from facenet_pytorch import MTCNN
import cv2
import torch
import numpy as np
from tqdm import tqdm
import glob
import os

# 🔧 MTCNN face detector (more sensitive)
mtcnn = MTCNN(
    image_size=128,
    margin=0,
    keep_all=True,
    thresholds=[0.4, 0.5, 0.5],
    post_process=False,
    device='cuda' if torch.cuda.is_available() else 'cpu'
)

from google.colab import drive
drive.mount('/content/drive')

DATASET_PATH = "/content/drive/MyDrive/deepfake_project/deepfake_dataset/FaceForensics_Ready"
REAL_VIDEOS = glob.glob(f"{DATASET_PATH}/real/*.mp4")
FAKE_VIDEOS = glob.glob(f"{DATASET_PATH}/fake/*.mp4")

print("Real videos:", len(REAL_VIDEOS))
print("Fake videos:", len(FAKE_VIDEOS))

mtcnn = MTCNN(image_size=128, margin=0, keep_all=True, post_process=False, device='cuda' if torch.cuda.is_available() else 'cpu')

def extract_faces_mtcnn(video_path, every_n_frames=5):
    cap = cv2.VideoCapture(video_path)
    frames = []
    frame_count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        if frame_count % every_n_frames == 0:
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            faces = mtcnn(rgb_frame)  # This returns cropped face tensors
            if faces is not None:
                for face in faces:
                    try:
                        face_np = face.permute(1, 2, 0).cpu().numpy().astype('float32') / 255.0
                        face_resized = cv2.resize(face_np, (128, 128))
                        frames.append(face_resized)
                    except:
                        continue
        frame_count += 1

    cap.release()
    return frames

from torchvision import transforms
import torch

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

real_faces = []

print("🔄 Extracting Real Faces...")
for video in tqdm(REAL_VIDEOS[:10], desc="Real"):
    faces = extract_faces_mtcnn(video)
    if faces:
        real_faces.extend([transform(f) for f in faces])

print(f"✅ Real faces collected: {len(real_faces)}")

if real_faces:
    torch.save(torch.stack(real_faces), "/content/real_faces.pt")
    print("✅ Saved real_faces.pt")
else:
    print("❌ No real faces detected.")

import os
os.path.exists("/content/real_faces.pt")

!cp /content/real_faces.pt /content/drive/MyDrive/deepfake_project/real_faces.pt