# -*- coding: utf-8 -*-
"""hybrid_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bc8ozPZp8xXFBua5js3OpEG9c3RL1KkQ
"""

from google.colab import drive
drive.mount('/content/drive')

import torch

# Load real face tensors from file
real_faces = torch.load("/content/drive/MyDrive/deepfake_project/real_faces.pt")
real_labels = torch.ones(len(real_faces))  # Label = 1 for real

import torch.nn.functional as F

# Function to create fake faces from real ones (blurred + noise)
def simulate_fake_faces(tensors):
    blurred = F.avg_pool2d(tensors, kernel_size=3, stride=1, padding=1)
    noise = blurred + 0.2 * torch.randn_like(blurred)
    return torch.clamp(noise, -1.0, 1.0)

# Use half of real_faces to simulate fake ones
fake_faces = simulate_fake_faces(real_faces[:len(real_faces)//2])
fake_labels = torch.zeros(len(fake_faces))  # Label = 0 for fake

# Combine faces and labels
data = torch.cat([real_faces, fake_faces], dim=0)
labels = torch.cat([real_labels, fake_labels], dim=0)

from torch.utils.data import TensorDataset, DataLoader, random_split

# Create dataset and split into train/test
dataset = TensorDataset(data, labels)
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_ds, test_ds = random_split(dataset, [train_size, test_size])

# Data loaders
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
test_loader = DataLoader(test_ds, batch_size=32)

import torch.nn as nn
import torch.nn.functional as F

class HybridDeepfakeDetector(nn.Module):
    def __init__(self):
        super().__init__()

        # CNN backbone
        self.cnn = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2)
        )
        # RNN for temporal context (even if simulating single-frame, future-proofed)
        self.rnn = nn.GRU(input_size=64 * 32 * 32, hidden_size=128, batch_first=True)
        # Transformer encoder
        transformer_layer = nn.TransformerEncoderLayer(d_model=128, nhead=4)
        self.transformer = nn.TransformerEncoder(transformer_layer, num_layers=1)

        # Fully connected head
        self.fc = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )
    def forward(self, x):
        batch_size = x.size(0)
        x = self.cnn(x)               # -> (B, 64, 32, 32)
        x = x.view(batch_size, -1)    # -> (B, features)
        x = x.unsqueeze(1)            # -> (B, 1, features)

        _, h_n = self.rnn(x)          # -> h_n: (1, B, 128)
        x = h_n.permute(1, 0, 2)      # -> (B, 1, 128)

        x = self.transformer(x)       # -> (B, 1, 128)
        x = x.squeeze(1)              # -> (B, 128)

        return self.fc(x)             # -> (B, 1)

import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = HybridDeepfakeDetector().to(device)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

train_losses = []
train_accuracies = []

# Training loop
for epoch in range(5):  # Increase epochs if needed
    model.train()
    total_loss = 0

    for images, targets in train_loader:
        images, targets = images.to(device), targets.to(device)
        outputs = model(images).squeeze()
        loss = criterion(outputs, targets)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    train_losses.append(avg_loss)

    # 🟩 Move this block inside the loop
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for images, targets in train_loader:
            images, targets = images.to(device), targets.to(device)
            outputs = model(images).squeeze()
            preds = (outputs > 0.5).float()
            correct += (preds == targets).sum().item()
            total += targets.size(0)

    train_accuracy = correct / total
    train_accuracies.append(train_accuracy)

    print(f"📘 Epoch {epoch+1} | Loss: {avg_loss:.4f} | Accuracy: {train_accuracy*100:.2f}%")

model.eval()
correct, total = 0, 0

with torch.no_grad():
    for images, targets in test_loader:
        images, targets = images.to(device), targets.to(device)
        outputs = model(images).squeeze()
        preds = (outputs > 0.5).float()
        correct += (preds == targets).sum().item()
        total += targets.size(0)

accuracy = correct / total
print(f"✅ Test Accuracy: {accuracy*100:.2f}%")

torch.save(model.state_dict(), "/content/hybrid_detector.pt")
print("✅ Model saved as hybrid_detector.pt")

!cp /content/hybrid_detector.pt /content/drive/MyDrive/deepfake_project/